---

- name: Get Plugins
  get_url:
    url: "{{ pluginsurl }}"
    dest: "{{ download_dir }}/{{ pluginssrc }}.tar.gz"

- name: Unpack Plugin source files
  unarchive:
    src: "{{ download_dir }}/{{ pluginssrc }}.tar.gz"
    dest: "{{ download_dir }}"
    remote_src: yes

- name: Setup Plugins
  command: ./tools/setup
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "{{ download_dir }}/{{ pluginssrc }}/Makefile.am"

- name: Configure Plugins
  command: ./configure --with-nagios-user={{ monitoring_user }} --with-nagios-group=nagios
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "{{ download_dir }}/{{ pluginssrc }}/Makefile"

- name: Make Plugins
  command: make
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "{{ download_dir }}/{{ pluginssrc }}/plugins/check_ping"

- name: Make Install Plugins
  command: make install
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "/usr/local/nagios/libexec/check_icmp"