---

- name: Get Plugins
  get_url:
    url: "{{ nagios_plugins_url }}"
    dest: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}.tar.gz"

- name: Unpack Plugin source files
  unarchive:
    src: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}.tar.gz"
    dest: "{{ nagios_download_dir }}"
    remote_src: true

- name: Setup Plugins
  command: ./tools/setup
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}"
    creates: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}/Makefile.in"

- name: Configure Plugins
  command: ./configure --with-nagios-user={{ nagios_monitoring_user }} --with-nagios-group=nagios
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}"
    creates: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}/Makefile"

- name: Make Plugins
  command: make
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}"
    creates: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}/plugins/check_ping"

- name: Make Install Plugins
  command: make install
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_plugins_src }}"
    creates: "/usr/local/nagios/libexec/check_icmp"
