---

- name: Get Plugins
  get_url:
    url: "{{ pluginsurl }}"
    dest: "{{ download_dir }}/{{ pluginssrc }}.tar.gz"

- name: Unpack Plugin source files
  unarchive:
    src: "{{ download_dir }}/{{ pluginssrc }}.tar.gz"
    dest: "{{ download_dir }}"
    remote_src: true

- name: Configure Plugins
  shell: ./configure --with-nagios-user={{ monitoring_user }} --with-nagios-group=nagios --with-openssl=/usr/bin/openssl
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "{{ download_dir }}/{{ pluginssrc }}/Makefile"

- name: Make Plugins
  shell:  make
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "{{ download_dir }}/{{ pluginssrc }}/plugins/check_ping"

- name: Make Install Plugins
  shell:  make install
  args:
    chdir: "{{ download_dir }}/{{ pluginssrc }}"
    creates: "creates=/usr/local/nagios/libexec/check_ping"