---

- name: GET Nagios
  get_url:
    url: "{{ nagios_url }}"
    dest: "{{ nagios_download_dir }}/{{ nagios_src }}.tar.gz"

- name: Unpack Nagios source files
  unarchive:
    src: "{{ nagios_download_dir }}/{{ nagios_src }}.tar.gz"
    dest: "{{ nagios_download_dir }}"
    remote_src: yes

- name: Set upgrade as not required by default
  set_fact:
    nagios_upgrade_required: false

# https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/upgrading.html
- name: check if nagios main.php exists
  stat:
    path: /usr/local/nagios/share/main.php
  register: nagios_mainphp_file

- block:

  - name: read nagios installed version
    shell: head /usr/local/nagios/share/main.php | grep "this_version" | cut -d"=" -f 2 | tr --delete ";" | tr --delete "'" | xargs echo -n
    changed_when: false
    register: cmd_nagios_version
    tags:
      - skip_ansible_lint
    check_mode: no

  - name: Check if upgrade is required
    set_fact:
      nagios_upgrade_required: true
    when: cmd_nagios_version.stdout != nagios_version
  
  when: nagios_mainphp_file.stat.exists

- name: backup files before clean
  copy: 
    src: "{{ item }}"
    dest: "{{ item }}.bkp"
    force: yes
  with_items:
    - "/usr/local/nagios/share/main.php"
    - "/usr/local/nagios/share/index.php"
    - "/usr/local/nagios/share/side.php"
    - "{{ nagios_httpd_location }}/nagios.conf"
    - "/usr/local/nagios/bin/nagios"
    - "/usr/local/nagios/include/nagios/nagios.h"
    - "/etc/init.d/nagios"
  when: nagios_upgrade_required
  failed_when: false

- name: Clean files before upgrade
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/local/nagios/share/main.php"
    - "/usr/local/nagios/share/index.php"
    - "/usr/local/nagios/share/side.php"
    - "{{ nagios_httpd_location }}/nagios.conf"
    - "/usr/local/nagios/bin/nagios"
    - "/usr/local/nagios/var/rw"
    - "/usr/local/nagios/include/nagios/nagios.h"
    - "/etc/init.d/nagios"
  when: nagios_upgrade_required
  notify: restart nagios

- name: Configure Nagios
  command: ./configure --with-command-group={{ nagios_monitoring_command_group }} --with-nagios-user={{ nagios_monitoring_user }}
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: "{{ nagios_download_dir }}/{{ nagios_src }}/Makefile"

- name: Make all
  command: make all
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: "{{ nagios_download_dir }}/{{ nagios_src }}/base/nagios"

- name: Make install
  command: make install
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: /usr/local/nagios/bin/nagios

- name: Make install-config
  command: make install-config
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: /usr/local/nagios/etc/nagios.cfg

- name: Make install-init
  command: make install-init
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: "{{ nagios_init }}"
  notify: restart nagios

- name: Make install-commandmode
  command: make install-commandmode
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: /usr/local/nagios/var/rw
  notify: restart nagios

- name: Make install-config
  command: make install-config
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: /usr/local/nagios/etc/nagios.cfg

- name: Make install-webconf
  command: make install-webconf
  args:
    chdir: "{{ nagios_download_dir }}/{{ nagios_src }}"
    creates: "{{ nagios_httpd_location }}/nagios.conf"
  notify: restart apache

- name: Ensure Nagios is enabled on boot
  service:
    name: nagios
    enabled: yes
