---
# tasks file for nagios
- block:

  - include: load-variables.yml

  - include: setup-RedHat-family-prerequisites.yml
    when: ansible_os_family == 'RedHat'

  - include: setup-Debian-family-prerequisites.yml
    when: ansible_os_family == 'Debian'

  - include: build-nagios.yml

  - include: build-plugins.yml

  - include: setup-selinux.yml
    when: ansible_os_family == 'RedHat'

  when: ansible_version.full < 2.4


- block:

  - include_tasks: load-variables.yml

  - include_tasks: setup-RedHat-family-prerequisites.yml
    when: ansible_os_family == 'RedHat'

  - include_tasks: setup-Debian-family-prerequisites.yml
    when: ansible_os_family == 'Debian'

  - include_tasks: build-nagios.yml

  - include_tasks: build-plugins.yml

  - include_tasks: setup-selinux.yml
    when: ansible_os_family == 'RedHat'

  when: ansible_version.full >= 2.4

- block:
    - name: Activate Nagios site on Ubuntu 14.04
      file:
        src: /etc/apache2/conf-available/nagios.conf
        dest: /etc/apache2/conf-enabled/nagios.conf
        state: link
        owner: root
        group: root
      notify: restart apache

    - name: Enable CGI
      apache2_module:
        name: cgi
        state: present
      notify: restart apache

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Enable version
  file:
    src: ../mods-available/version.load
    dest: /etc/apache2/mods-enabled/version.load
    state: link
  notify: restart apache
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'

#- name: Fix Nagios startup on Debian
#  shell: cd /etc/rc2.d && ln -s ../init.d/nagios S18nagios creates=/etc/rc2.d/S18nagios
#  when: ansible_distribution == 'Debian'

- name: http service state
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
