---
# tasks file for nagios

- include: load-variables.yml

- include: setup-epel.yml
  when: ansible_os_family == 'RedHat'

- include: setup-prerequisites.yml

- include: setup-users.yml

- include: build-nagios.yml

- include: build-plugins.yml

- include: setup-selinux.yml
  when: ansible_os_family == 'RedHat'

- block:
    - name: Activate Nagios site on Ubuntu 14.04
      file:
        src: /etc/apache2/conf-available/nagios.conf
        dest: /etc/apache2/conf-enabled/nagios.conf
        state: link
        owner: root
        group: root
      notify: restart apache

    - name: Enable CGI
      apache2_module:
        name: cgi
        state: present
      notify: restart apache

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Enable version
  file:
    src: ../mods-available/version.load
    dest: /etc/apache2/mods-enabled/version.load
    state: link
  notify: restart apache
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'

#- name: Fix Nagios startup on Debian
#  shell: cd /etc/rc2.d && ln -s ../init.d/nagios S18nagios creates=/etc/rc2.d/S18nagios
#  when: ansible_distribution == 'Debian'

- name: http service state
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
