---
# tasks file for nagios

- name: Ensure download directory is present
  file:
    path: "{{ download_dir }}"
    state: directory

- include_tasks: load-variables.yml

- include_tasks: setup-RedHat-family-prerequisites.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian-family-prerequisites.yml
  when: ansible_os_family == 'Debian'

- name: Create nagcmd group
  group:
    name: "{{ monitoring_command_group }}"
    state: present

- name: Create nagios user
  user:
    name: "{{ monitoring_user }}"
    groups: "{{ monitoring_command_group }}"
    state: present

- name: Add apache user to nagcmd group
  user:
    name: "{{ apache_user }}"
    groups: "{{ monitoring_command_group }}"
    state: present

- include_tasks: build-nagios.yml

- include_tasks: build-plugins.yml

- include_tasks: setup-selinux.yml
  when: ansible_os_family == 'RedHat'

- block:
    - name: Activate Nagios site on Ubuntu 14.04
      file:
        src: /etc/apache2/conf-available/nagios.conf
        dest: /etc/apache2/conf-enabled/nagios.conf
        state: link
        owner: root
        group: root
      notify: restart apache

    - name: Enable CGI
      apache2_module:
        name: cgi
        state: present
      notify: restart apache

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Enable version
  file:
    src: ../mods-available/version.load
    dest: /etc/apache2/mods-enabled/version.load
    state: link
  notify: restart apache
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'

#- name: Fix Nagios startup on Debian
#  shell: cd /etc/rc2.d && ln -s ../init.d/nagios S18nagios creates=/etc/rc2.d/S18nagios
#  when: ansible_distribution == 'Debian'

- name: http service state
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
