---
# tasks file for nagios

- name: Ensure download directory is present
  file:
    path: "{{ nagios_download_dir }}"
    state: directory

- include: load-variables.yml

- include: setup-epel.yml
  when: ansible_os_family == 'RedHat'

- include: setup-prerequisites.yml

- include: setup-users.yml

- include: build-nagios.yml

- include: setup-apache.yml

- include: build-plugins.yml

- include: setup-selinux.yml
  when: ansible_os_family == 'RedHat'