---
- block:

    - name: Install Nagios prerequisites with apt
      apt:
        name: "{{ nagios_prerequisites }}"
        state: present
        update_cache: true

    - name: Install Plugin prerequisites with apt
      apt:
        name: "{{ nagios_plugins_prerequisites }}"
        state: present

  when: ansible_os_family == "Debian"

- block:

    - name: Install Nagios prerequisites with yum
      yum:
        name: "{{ nagios_prerequisites }}"
        state: present
        update_cache: true

    - name: Install Plugin prerequisites with yum
      yum:
        name: "{{ nagios_plugins_prerequisites }}"
        state: present

  when: ansible_distribution == "CentOS"

- block:

    - name: Install Nagios prerequisites with dnf
      dnf:
        name: "{{ nagios_prerequisites }}"
        state: present

    - name: Install Plugin prerequisites with dnf
      dnf:
        name: "{{ nagios_plugins_prerequisites }}"
        state: present

  when: ansible_distribution == "Fedora"

- name: Install Ansible prerequisites
  package:
    name: python-passlib
    state: present
