---

- name: Create nagcmd group
  group:
    name: "{{ nagios_monitoring_command_group }}"
    state: present

- name: Create nagios user
  user:
    name: "{{ nagios_monitoring_user }}"
    groups: "{{ nagios_monitoring_command_group }}"
    state: present

- name: Add apache user to nagcmd group
  user:
    name: "{{ apache_user }}"
    groups: "{{ nagios_monitoring_command_group }}"
    state: present