---

- block:

    - name: Install Nagios prerequisites with apt
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items: "{{ nagios_prerequisites }}"

    - name: Install Plugin prerequisites with apt
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ nagios_plugins_prerequisites }}"

  when: ansible_os_family == "Debian"

- block:

    - name: Install Nagios prerequisites with yum
      yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items: "{{ nagios_prerequisites }}"

    - name: Install Plugin prerequisites with yum
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ nagios_plugins_prerequisites }}"

  when: ansible_os_family == "RedHat"

- name: Install Ansible prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib

- name: Ensure Apache is enabled on boot
  service:
    name: "{{ apache_service }}"
    enabled: true
