---

- name: Install Nagios prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nagios_prerequisites }}"

- name: Install Plugin prerequisites for Debian family
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nagios_plugins_prerequisites }}"

- name: Install Ansible prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib

- name: Ensure Apache is enabled on boot
  service:
    name: "{{ apache_service }}"
    enabled: yes
