---

- name: Enable CGI
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - cgi
    - rewrite
  when: ansible_os_family == "Debian" and ansible_distribution_version != '12.04'
  notify: restart apache

- name: Set htpasswd for gui users
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    state: present
  with_items: "{{ nagios_users }}"

- name: Enable version
  file:
    src: ../mods-available/version.load
    dest: /etc/apache2/mods-enabled/version.load
    state: link
  notify: restart apache
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'
