---

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: False

- name: Install Nagios prerequisites for Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - gcc
    - libc6
    - libmcrypt-dev
    - make
    - libssl-dev
    - bc
    - gawk
    - dc
    - build-essential
    - snmp
    - libnet-snmp-perl
    - gettext
  when: ansible_distribution == 'Ubuntu'

#- name: setup-Debian | Remove Nagios3 and check-mk-livestatus for Ubuntu
#  apt:
#    name: "{{ item }}"
#    state: absent
#  with_items:
#    - nagios3
#    - nagios3-core
#    - check-mk-livestatus
#  when: ansible_role_nagios_remove_packages

- name: Install Plugin prerequisites for Debian family
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - gcc
    - libc6
    - libmcrypt-dev
    - make
    - libssl-dev
    - bc
    - gawk
    - dc
    - build-essential
    - snmp
    - libnet-snmp-perl
    - gettext
  when: ansible_distribution == 'Debian'

- name: Install ansible prerequisites for Debian family
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib


#- name: Install ansible prerequisites for Debian family
#  apt:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - python-urllib3 # fix SSL error when using ansible module get_url https://github.com/ansible/ansible/issues/23642
#
#- name: Install Plugin prerequisites for Ubuntu
#  apt:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - libradiusclient-ng-dev
#  when: ansible_distribution == 'Ubuntu'
