---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/_rules/.yamllint

platforms:
  - name: CentOS7
    image: lansible/centos:7

  - name: CentOS6
    image: lansible/centos:6

  - name: Debian9
    image: lansible/debian:9

  - name: Debian8
    image: lansible/debian:8

  - name: Fedora27
    image: lansible/fedora:27

  - name: Fedora26
    image: lansible/fedora:26

  - name: Ubuntu1604
    image: lansible/ubuntu:16.04

  - name: Ubuntu1404
    image: lansible/ubuntu:16.04

provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: molecule/_rules/.ansible-lint

scenario:
  name: default

verifier:
  name: goss
  enabled: false
